name: Deploy to Prod

on:
  push:
    branches:
    - master

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    env:
      REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY_PROD }}
      REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN_PROD }}
      REACT_APP_FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL_PROD }}
      REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID_PROD }}
      REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET_PROD }}
      REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID_PROD }}
      REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID_PROD }}
      REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID_PROD }}

    steps:
    - name: Use Checkout
      uses: actions/checkout@master
    - name: Setup Node
      uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - name: Install functions npm packages
      run: |
        yarn install
        cd functions
        yarn install
    - name:  Deploy Firebase Functions
      uses: w9jds/firebase-action@master
      with:
          args: deploy --only functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PROD }}
        PROJECT_ID: prod
    - name: Install project npm packages
      run: |
        yarn install
        yarn run build
    - name: Deploy Firebase Hosting, Database, Storage, Firestore
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting,database,storage,firestore
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PROD }}
        PROJECT_ID: prod
